{% set name = "jaeger-client" %}
{% set version = "4.6.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: a6b7c6a0d011870f9680f9c4922fb3e5

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  # uses fcntl module, which is not on windows.
  #    see https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows for potential substitute.
  skip: true  # [win]
  # can't be noarch because of windows incompatbility

requirements:
  host:
    - python
    - pip
  run:
    - python
    - threadloop >=1,<2
    - opentracing >=2.1,<3.0
    - thrift
    - tornado >=4.3

test:
  imports:
    - jaeger_client

about:
  home: https://github.com/uber/jaeger-client-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Jaeger Python OpenTracing Tracer implementation

extra:
  recipe-maintainers:
    - baszalmstra
    - msarahan
    - scopatz
