{% set name = "jaeger-client" %}
{% set version = "4.1.0" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: bec966c68cf0eb3bd2468d62168fb492

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  # uses fcntl module, which is not on windows.
  #    see https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows for potential substitute.
  skip: True   # [win]
  # can't be noarch because of windows incompatbility

requirements:
  build:
    - python
    - pip
  run:
    - python
    - threadloop
    - opentracing
    - thrift
    - tornado

test:
  imports:
    - jaeger_client

about:
  home: https://github.com/uber/jaeger-client-python
  license: MIT
  summary: Jaeger Python OpenTracing Tracer implementation

extra:
  recipe-maintainers:
    - msarahan
