{% set name = "jaeger-client" %}
{% set version = "4.3.0" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 86d27b8446d3e4c96332896b41307bf7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  # uses fcntl module, which is not on windows.
  #    see https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows for potential substitute.
  skip: True   # [win]
  # can't be noarch because of windows incompatbility

requirements:
  host:
    - python
    - pip
  run:
    - python
    - threadloop >=1,<2
    - opentracing >=2.1,<3.0
    - thrift
    - tornado >=4.3

test:
  imports:
    - jaeger_client

about:
  home: https://github.com/uber/jaeger-client-python
  license: MIT
  summary: Jaeger Python OpenTracing Tracer implementation

extra:
  recipe-maintainers:
    - msarahan
    - scopatz
