appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KDgAo34Cw66L5RPCjeLIqoepRDHhZFxO+/uaiL67IPtiet0vi6xXsqMd3/Z8J627grUEbGw09OPEVMDSo2Svg5NOqG6Ccql2Yu8E/qoQWOtZ4DpD7MQA/UQo7eihNFMCnDbAyFiw4RZ9XkDzogrlKQ7veNMrXWWiZ3Xon50hu5e8q4qjWFbENZEcxyEl4hDVfhLJBfMLsX3gDEWe5J3rWmab/6XqQsHrOgWwcptOTLI4VaalXOkTJPLj7EnNf0p9CauOTfjhxC7DbzqgXi89Bb02/FRxNizK9iE6B9q0EsyJ4gCqu5UONH1oDARGHhLoM+UbEZGR6mQaxEvzlUOXbQFWHfnoIEIWehhe22YFFDZ9IPrVV74IOM+Xv7LzlOD7uU+9Occyf8nnmABBNfoxrBNTQ5UMOL8q6lRHNVbq+BnIXNlVyCftRxJt1F+e6sUS3DWYYNhZPfcAzkOpkwynmjyO4OFQYsrlsjv/cnBPEsJqAbu58Sj2lseXUPGJ7JAB1ggmIGcLgNb+Y/YCedQHWxQmI8QvZTvmtAkeF7t2Ys13PLY4orU295Bd4LIunOCnz3JMiF10kyC5A+YEnHOTp14EwwKmTTnhm3PE5pWDYQR0AZZs0vEhvk/Xs9sNkOCw2E7wh3qURkwC086yc+Q+SfVmREyP9m0PDxdV6CsnLyI=}
conda_forge_output_validation: true
